#!/bin/bash
export DOCKER_CLI_EXPERIMENTAL=enabled
#
echo "DOCKERFILE_PATH=${DOCKERFILE_PATH}"
echo "DOCKER_REPO=${DOCKER_REPO}"
echo "DOCKER_TAG=${DOCKER_TAG}"
echo "IMAGE_NAME=${IMAGE_NAME}"
#
# docker manifest create raymondwcs/node raymondwcs/node:latest
# docker manifest annotate raymondwcs/node raymondwcs/node:latest --os linux --arch arm64
export ARCH=`echo "${DOCKERFILE_PATH}" | cut -d'.' -f2`
echo "ARCH=${ARCH}"
if [ $ARCH == "arm64" ]
then
    # DOCKER_TAG="arm64v8-latest"
    echo ">>> Create manifest and annotate..."
    docker manifest create ${DOCKER_REPO} "${DOCKER_REPO}:latest" "${DOCKER_REPO}:${DOCKER_TAG}"
    docker manifest annotate ${DOCKER_REPO} "${DOCKER_REPO}:${DOCKER_TAG}" --os linux --arch ${ARCH}
    echo ">>> Done!"
fi